### ISSUE TITLE
Settings option to NOT set background color in has-annotation spans

### ISSUE THREAD

**Issue by mlava** [c3founder/ccc-roam-pdf-2#8]
I'm using this to make my notes still readable:

`.rm-block-ref.has-annotation span {
  background-color: unset !important;  
}`

**Comment by c3founder** [comment]
Yes, I'm going to add a couple of options in the next update:

1. yes/no named color in the block
2. all/none/some block color (in some, you can, for example, say red and green appear on the block)
3. various named color palettes (currently there are ~140 of them) with smaller number of colors (say you want all rgb colors get mapped to only red/yellow/green/blue/purple)

**Comment by c3founder** [comment]
A variant of this will be released in v2.1
